### ISSUE TITLE
Conversions takes significantly more time compared to converting in browser

### ISSUE THREAD

**Issue by paulius-petkus** [ConvertAPI/convertapi-python#46] opened 2024-05-31 07:59 UTC
Tested PDF to Squeeze with 90MB Pdf file:
https://www.convertapi.com/a/api/pdf-to-squeeze#snippet=python
It took 4.5-5s to convert + file upload and download couple seconds. So **<10s** overall.
![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/df279bc3-5b67-4004-b8a4-d0c6c52063bf)

With python lib it took **>60s**:
![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/ea85c36d-5f05-4282-8333-f60f5a88beff)

**Comment by laurynas-convertapi** [comment] 2024-05-31 13:58
Hi @paulius-petkus,

could you please measure individual steps (upload, api, download) to help us understand better where the major slowdown is.

You can measure like this:

```python

start_time = time.time()
upload_io = convertapi.UploadIO(open(file, 'rb'))
print(upload_io.file_id)
print("Upload time taken: %s seconds" % (time.time() - start_time))

start_time = time.time()
result = convertapi.convert('squeeze', {'File': upload_io}, from_format='pdf')
print("API time taken: %s seconds" % (time.time() - start_time))

start_time = time.time()
saved_files = result.save_files(tempfile.gettempdir())
print("Download time taken: %s seconds" % (time.time() - start_time))

print("The PDF saved to %s" % saved_files)
```

**Comment by paulius-petkus** [comment] 2024-06-03 06:23
@laurynas-convertapi Hello, sure.

Seems Upload is the biggest problem:
![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/1e7db1f3-17ce-410f-aed7-514ce846f706)

**Comment by laurynas-convertapi** [comment] 2024-06-08 18:48
@paulius-petkus thanks! Very helpful.

Can you try adding this to the to of the script and see if it helps to reduce upload time:

```python
from http.client import HTTPConnection
HTTPConnection.__init__.__defaults__ = tuple(
    x if x != 8192 else 64*1024
    for x in HTTPConnection.__init__.__defaults__
)
```

**Comment by paulius-petkus** [comment] 2024-06-10 07:18
@laurynas-convertapi  I have added it to the very beginning of the script, but it didn't help. Or should I add it somewhere else?

My current code snippet and results: 
![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/1309573d-9575-4e72-ba77-51e567c15754)

**Comment by laurynas-convertapi** [comment] 2024-06-10 18:46
Yes, it should be at the top. Strange it didn't have any effect, because I think the issue might be related with python httplib, as described here:
https://github.com/psf/requests/issues/2181#issuecomment-713823366

Here is another suggestion, maybe this would work?
https://stackoverflow.com/a/39518613

**Comment by paulius-petkus** [comment] 2024-06-12 07:17
Hi @laurynas-convertapi, as far as I understand you do not have these problems and conversion takes way less time for you? If the problem does not reproduce on your machine, I think I will investigate what is wrong.

**Comment by laurynas-convertapi** [comment] 2024-06-13 16:42
@paulius-petkus yes, I can't see significant difference when uploading file via command line curl (tried both on linux and mac) and running python script (python version 3.9.14).

For me [100MB file](https://link.testfile.org/PDF100MB) upload takes ~15s on 5G connection.

If you have an option to run curl, I suggest testing like this:
```shell
time curl -F 'file=@files/100mb.pdf' https://v2.convertapi.com/upload
```

**Comment by paulius-petkus** [comment] 2024-06-17 09:40
It seems everything is fine when I run it with curl. Here is my code that ran in windows command prompt:
```
@echo off
set start_time=%time%
curl -X POST https://v2.convertapi.com/upload?Secret=my_secret -F "File=@C:/Users/petku/Desktop/TEMP/large1.pdf"
set end_time=%time%
echo Start Time: %start_time%
echo End Time: %end_time%
```
it took few seconds:
![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/15a7cfbf-8994-43a1-8731-32c9fe6d8c41)

When I do the upload document with request instead of using our library, it also works fast (3-7s instead of 45-55s). My python version: 3.12.1

Here is full code with only secret changed:
```
import requests
import time
import convertapi
import tempfile

api_secret = 'XXXXXXXXX'

start_time = time.time()
file_path = 'C:/Users/petku/Desktop/TEMP/large1.pdf'
api_url = 'https://v2.convertapi.com/upload'
with open(file_path, 'rb') as file:
    response = requests.post(api_url, files={'file': file}, headers={'Authorization': f'Bearer {api_secret}'})
    upload_io = response.json()
print("Upload time taken: %s seconds" % (time.time() - start_time))

convertapi.api_secret = api_secret
start_time = time.time()
result = convertapi.convert('squeeze', {'File': upload_io['Url']}, from_format='pdf')
print("API time taken: %s seconds" % (time.time() - start_time))

start_time = time.time()
saved_files = result.save_files(tempfile.gettempdir())
print("Download time taken: %s seconds" % (time.time() - start_time))

print("The PDF saved to %s" % saved_files)

```

**Comment by laurynas-convertapi** [comment] 2024-06-18 18:45
Hi @paulius-petkus, very interesting, if the same file upload using requests library directly is significantly faster. Thanks for the example, I will investigate it.

**Comment by laurynas-convertapi** [comment] 2024-06-20 18:21
@paulius-petkus could you please try comparing following examples on your system? I don't see the difference on mine, but maybe you'll get different results:

Your adjusted version with `files`:
```python
import requests
import time

file_path = 'files/test100mb.pdf'
api_url = 'https://v2.convertapi.com/upload'

start_time = time.time()

with open(file_path, 'rb') as file:
    s = requests.Session()
    response = requests.post(api_url, files={'file': file})
    upload_io = response.json()
    print(upload_io['FileId'])

print("Upload time taken: %s seconds" % (time.time() - start_time))

```

Version with `data` (as library uses):
```python
import requests
import time

file_path = 'files/test100mb.pdf'
api_url = 'https://v2.convertapi.com/upload'

start_time = time.time()

with open(file_path, 'rb') as file:
    s = requests.Session()
    headers = { 'Content-Disposition': "attachment; filename*=UTF-8''test.pdf" }
    response = s.post(api_url, data = file, headers = headers)
    upload_io = response.json()
    print(upload_io['FileId'])

print("Upload time taken: %s seconds" % (time.time() - start_time))
```

**Comment by paulius-petkus** [comment] 2024-06-21 15:10
Hi, both of these solutions works fast for me. It takes ~2s to upload that 100mb file. It seems the problem occurs on windows, cause me and Tomas both use Windows and we both have this problem.

We are not familiar with python code. But maybe the problem is with those chunks / headers creating in lib? - Maybe we can use most simple upload logic? Example in my previous comment (below curl code) works fast.

**Comment by tomasr78** [comment] 2024-06-21 15:18
I suggest using this code for uploading, it works fine on Windows, does not require manual content disposition building, and has a lower chance to introduce bugs.

```
import requests
import time

file_path = 'files/test100mb.pdf'
api_url = 'https://v2.convertapi.com/upload'

start_time = time.time()

with open(file_path, 'rb') as file:
    s = requests.Session()
    response = requests.post(api_url, files={'file': file})
    upload_io = response.json()
    print(upload_io['FileId'])

print("Upload time taken: %s seconds" % (time.time() - start_time))
```

**Comment by laurynas** [comment] 2024-06-21 15:40
@paulius-petkus by chunks, do you mean download chunks?
https://github.com/ConvertAPI/convertapi-python/blob/master/convertapi/client.py#L35

I thought the issue is with file upload. I mean, we are trying to isolate the slow part. 

Can you confirm this code is slow on windows?
```python
start_time = time.time()
upload_io = convertapi.UploadIO(open(file, 'rb'))
print(upload_io.file_id)
print("Upload time taken: %s seconds" % (time.time() - start_time))
```

**Comment by laurynas-convertapi** [comment] 2024-06-21 15:53
@paulius-petkus by chunks, do you mean download chunks?
https://github.com/ConvertAPI/convertapi-python/blob/master/convertapi/client.py#L35

I thought the issue is with file upload. Can you confirm this code is slow on windows?
```python
start_time = time.time()
upload_io = convertapi.UploadIO(open(file, 'rb'))
print(upload_io.file_id)
print("Upload time taken: %s seconds" % (time.time() - start_time))
```

And if yes, let's try this, it mimics the logic of `convertapi.UploadIO`:
```python
import requests
import time

file_path = 'files/test100mb.pdf'
api_url = 'https://v2.convertapi.com/upload'

start_time = time.time()

with open(file_path, 'rb') as file:
    s = requests.Session()
    s.headers.update({ 'User-Agent': 'ConvertAPI-Python/test' })
    s.verify = True
    headers = { 'Content-Disposition': "attachment; filename*=UTF-8''test.pdf" }
    response = s.post(api_url, data = file, headers = headers, timeout = 1800)
    upload_io = response.json()
    print(upload_io['FileId'])

print("Upload time taken: %s seconds" % (time.time() - start_time))

```

**Comment by paulius-petkus** [comment] 2024-06-25 06:33
@laurynas-convertapi Yes you are absolutely right - the problem is with upload. I overseen client lib, sorry for the confusion.

Yes, I confirm that first code block is slow. It takes ~50s to upload my 100mb test file. Additionally, second code block is also the same slow. I have debugged and it seems, that "timeout" is causing the issue.

Without timeout upload is fast:
```
import requests
import time

file_path = 'C:/Users/petku/Desktop/TEMP/large1.pdf'
#file_path = 'C:/Users/petku/Desktop/TEMP/sdf.pdf'
api_url = 'https://v2.convertapi.com/upload'

start_time = time.time()

with open(file_path, 'rb') as file:
    s = requests.Session()
    response = requests.post(api_url, files={'file': file})
    upload_io = response.json()
    print(upload_io['FileId'])

print("Upload time taken: %s seconds" % (time.time() - start_time))
```
![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/8f6884cd-f306-4f8f-acdf-04422286b935)


And whole conversion (secret changed):
```
import requests
import time
import convertapi
import tempfile

api_secret = 'XXXXXXX'

start_time = time.time()
file_path = 'C:/Users/petku/Desktop/TEMP/large1.pdf'
api_url = 'https://v2.convertapi.com/upload'

with open(file_path, 'rb') as file:
    response = requests.post(api_url, files={'file': file}, headers={'Authorization': f'Bearer {api_secret}'})
    upload_io = response.json()
    
print("Upload time taken: %s seconds" % (time.time() - start_time))

convertapi.api_secret = api_secret
start_time = time.time()
result = convertapi.convert('squeeze', {'File': upload_io['Url']}, from_format='pdf')
print("API time taken: %s seconds" % (time.time() - start_time))

start_time = time.time()
saved_files = result.save_files(tempfile.gettempdir())
print("Download time taken: %s seconds" % (time.time() - start_time))

print("The PDF saved to %s" % saved_files)
```

![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/c93a58ea-9c27-43c3-a182-8a326c9a322d)

**Comment by laurynas-convertapi** [comment] 2024-06-25 19:05
@paulius-petkus very interesting finding that timeout param is causing the slowdown!

Which `requests` library version you are using? If not the latest, maybe you could check if you can reproduce this problem on latest 2.32.3 version?

Also could you please check if specifying timeout tuple (connect + request timeout) makes any difference:
```python
response = s.post(api_url, data = file, headers = headers, timeout = (3,1800))
```

And, just out of curiosity, does smaller timeout makes any difference:
```python
response = s.post(api_url, data = file, headers = headers, timeout = 60)
```

**Comment by paulius-petkus** [comment] 2024-06-26 07:20
@laurynas-convertapi requests version is 2.32.3.

Checked with tuple and with small timeout: both scenarios are same slow. Here are output results:
![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/d8958125-bf8b-43ca-a241-33ae2e0e9acf)

**Comment by laurynas-convertapi** [comment] 2024-06-30 16:01
@paulius-petkus sad to see it doesn't help. apparently there is some bug in the underlying libraries on Windows which causes the slowdown when timeout is specified.

Could you please try one more thing - just use standard convertapi python library  and set upload timeout to none:
```python
convertapi.upload_timeout = None
```
I guess it should help. If it works, we could consider changing upload_timeout default to `None`.

**Comment by paulius-petkus** [comment] 2024-07-01 06:41
@laurynas-convertapi yes this setting timeout to None improved results as expected.

The same 100mb file conversion results:
![image](https://github.com/ConvertAPI/convertapi-python/assets/162338583/cee2bb9e-fda0-4e36-829d-0aabcbc16ee2)

**Comment by tomasr78** [comment] 2024-07-23 08:28
@laurynas-convertapi, what is the status of this issue?

**Comment by laurynas-convertapi** [comment] 2024-09-14 07:56
@tomasr78 will change default upload and download to `None`:
https://github.com/ConvertAPI/convertapi-library-python/pull/51

**Comment by laurynas-convertapi** [comment] 2024-09-14 09:31
Released in version https://github.com/ConvertAPI/convertapi-library-python/releases/tag/v2.0.0

**Closed as completed by laurynas-convertapi** 2024-09-14 09:31 UTC
